# Mandatory settings

name: Primitive Artists
paginate: 5
paginate_path: "/posts/page/:num/"
baseurl: /
blog_theme: light # Or use dark

# Optional settings

discus_identifier: primitiveartists
ga_analytics: # Add your GA Tracking Id
rss_enabled: true # Change to false if not
social:
  facebook: # Add your Facebook handle
  twitter: # Add your Twitter handle
  email: anand@primitiveartists.com

# Important settings

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
permalink: /posts/:slug
